[proxy]
port = 3128
bind_address = "0.0.0.0"

[management]
port = 8080
bind_address = "0.0.0.0"

[dns] # <-- EKLENDİ
enabled = true
port = 53
bind_address = "0.0.0.0"

[certs]
path = "./.certs"

[cache]
path = "./.cache"