[proxy]
port = 3128
bind_address = "0.0.0.0"

[management]
port = 8080
bind_address = "0.0.0.0"

[dns]
enabled = true
port = 8053 # <-- DEĞİŞİKLİK: Daha az kullanılan bir port
bind_address = "0.0.0.0"
response_ip = "127.0.0.1"

[certs]
path = "./.certs"

[cache]
path = "./.cache"