services:
  app:
    build: .
    container_name: sentiric-traffic-cache
    ports:
      - "3128:3128"
      - "8080:8080"
      - "53:53/udp"
    volumes:
      # --- MEVCUT SATIRLAR ---
      - ./config.toml:/app/config.toml
      - ./.certs:/app/.certs
      - ./.cache:/app/.cache
      - ./rules.toml:/app/rules.toml
    restart: unless-stopped