services:
  app:
    build: .
    container_name: sentiric-traffic-cache
    ports:
      - "3128:3128"
      - "8080:8080" # Yönetim arayüzü
      # - "53:53/udp" # DNS eklendiğinde bu satırı açacağız.      
    volumes:
      - ./crates:/app/crates
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - ./config.toml:/app/config.toml
      - ./.certs:/app/.certs
      - ./.cache:/app/.cache # <--- Cache'i de kalıcı hale getirelim
    restart: unless-stopped