FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    curl \
    dnsutils \
    jq \
    ca-certificates \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tests
COPY . .
RUN chmod +x test-runner.sh helpers.sh scenarios/*.sh

# Ana test koşucusunu çalıştır
CMD ["/test-runner.sh"]