[package]
name = "sentiric-cli"
version = "1.0.0"
edition = "2021"

[dependencies]
sentiric-service = { path = "../service", version = "1.0.0" }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }