name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*' # Sadece v0.1.0 gibi geçerli versiyon tag'lerinde tetiklenir

jobs:
  build-release:
    name: Build Cross-Platform Binaries
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        working-directory: ./web
        run: npm ci

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "crates/companion"
          args: ${{ matrix.platform == 'ubuntu-latest' && '--no-bundle' || '' }}

      # Workaround for https://github.com/tauri-apps/tauri/issues/7543
      - name: Build appimage separately
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cd crates/companion
          cargo tauri build -- --bundle appimage

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.platform }}
          path: |
            crates/companion/src-tauri/target/release/bundle/**/*.msi
            crates/companion/src-tauri/target/release/bundle/**/*.msi.zip
            crates/companion/src-tauri/target/release/bundle/**/*.dmg
            crates/companion/src-tauri/target/release/bundle/**/*.deb
            crates/companion/src-tauri/target/release/bundle/**/*.AppImage
            
  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*