name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libjavascriptcoregtk-4.1-dev
          cd /usr/lib/x86_64-linux-gnu/pkgconfig
          sudo ln -s webkit2gtk-4.1.pc webkit2gtk-4.0.pc
          sudo ln -s javascriptcoregtk-4.1.pc javascriptcoregtk-4.0.pc
          cd /usr/lib/x86_64-linux-gnu/
          sudo ln -s libwebkit2gtk-4.1.so libwebkit2gtk-4.0.so
          sudo ln -s libjavascriptcoregtk-4.1.so libjavascriptcoregtk-4.0.so

      - name: install frontend dependencies
        run: npm install --prefix web

      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "crates/companion"
          
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.tauri.outputs.dmgPath }}
            ${{ steps.tauri.outputs.msiPath }}
            ${{ steps.tauri.outputs.debPath }}
            ${{ steps.tauri.outputs.appImagePath }}