name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*' # Sadece v0.1.0 gibi geçerli versiyon tag'lerinde tetiklenir

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/sentiric-traffic-cache

jobs:
  # Bu iş artık yok, çünkü release.yml'i sadece biz (geliştiriciler)
  # bilinçli olarak tetikleyeceğiz. CI.yml'in testlerinden geçtiğini varsayıyoruz.

  create_release_and_build_binaries:
    name: Create Release and Build Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross-compilation tools
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Install cross-compilation targets
        run: |
          rustup target add x86_64-unknown-linux-gnu
          rustup target add x86_64-pc-windows-gnu
          # macOS için cross-compilation çok daha karmaşık, şimdilik bunu atlıyoruz.
          # İleride ayrı bir macOS runner'ı üzerinde derleyeceğiz.

      - name: Build binaries
        run: |
          cargo build -p sentiric-cli --release --target x86_64-unknown-linux-gnu
          cargo build -p sentiric-cli --release --target x86_64-pc-windows-gnu

      - name: Package binaries
        run: |
          tar -czvf sentiric-cli-linux-amd64.tar.gz -C target/x86_64-unknown-linux-gnu/release sentiric-cli
          zip sentiric-cli-windows-amd64.zip target/x86_64-pc-windows-gnu/release/sentiric-cli.exe
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sentiric-cli-linux-amd64.tar.gz
            sentiric-cli-windows-amd64.zip

  push_docker_image:
    name: Push Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}